### ISSUE TITLE
README.md may want to include information for springsecurity rules

### ISSUE THREAD

**Issue by harbdog** [dustindclark/grails-timezone-detection#2]
In my grails application I use the springsecurity plugin and have explicit permissions for each controller/page, so without adding anything extra after adding this plugin it went into an infinite loop  redirecting to the login page after adding <tz:detect /> to my main layout. 

Only after stopping the page loading process and going into the chrome debug console I found the URL it was trying to access as _/timezone_ within my context, so adding `'/timezone/**': ['permitAll']` inside my _grails.plugin.springsecurity.controllerAnnotations.staticRules_ was required to make it work.

**Comment by harbdog** [comment]
Also just found a typo in the README.md

```
<tg:show /> <!-- results in TimeZone ID (i.e. UTC, CST) -->
<tg:show attribute="displayName" /> <!-- results in TimeZone display name (i.e. Universal Time Coordinated, America/Chicago, etc) -->
```

Those didn't work, _tg_ is supposed to be _tz_ I guess:
`<tz:show/>`

**Comment by dustindclark** [comment]
@harbdog , thanks for the feedback.  I've updated/corrected the documentation.
